CREATE TABLE IF NOT EXISTS portfolios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    classroom_id INT NOT NULL,
    semester TINYINT NOT NULL,
    year INT NOT NULL,
    cover_photo_url VARCHAR(500) NULL,
    teacher_message TEXT NULL,
    teacher_message_corrected TEXT NULL,
    axis_movement_photos JSON NULL,
    axis_manual_photos JSON NULL,
    axis_stories_photos JSON NULL,
    axis_music_photos JSON NULL,
    axis_pca_photos JSON NULL,
    axis_movement_description TEXT NULL,
    axis_manual_description TEXT NULL,
    axis_stories_description TEXT NULL,
    axis_music_description TEXT NULL,
    axis_pca_description TEXT NULL,
    status ENUM('pending', 'finalized', 'revision_requested') DEFAULT 'pending',
    revision_notes TEXT NULL,
    revision_requested_by INT NULL,
    finalized_at DATETIME NULL,
    finalized_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,
    UNIQUE KEY unique_portfolio (classroom_id, semester, year),
    INDEX idx_portfolio_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
